server:
  port: 8060

spring:
  application:
    name: api-gateway

  eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/

  cloud:
    gateway:
      routes:
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/orders/**
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/payments/**
