spring:
  application:
    name: payment-service

  main:
    web-application-type: servlet

  cloud:
    circuitbreaker:
      resilience4j:
        instances:
          orderService:
            slidingWindowSize: 5
            failureRateThreshold: 50
            waitDurationInOpenState: 10s # Better format
            permittedNumberOfCallsInHalfOpenState: 2
            minimumNumberOfCalls: 1

  config:
    import: "optional:configserver:http://localhost:8088"
